name: survey_prototype
description: An example job survey app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  # Used for date formatting.
  intl: ^0.18.0
  provider: ^6.1.2
  realm: ^1.2.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  realm_common: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

# Image to show when app first loads, before any of our widgets are rendered.
# To regenerate: `dart run flutter_native_splash:create`
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/splash.jpg
  android: true
  ios: true
  web: true
